//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinearCalc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinearCalc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !---------------------Compensating Script
        ///!!---------------Some Definitions
        ///GLOBAL INT compStartPos, compStep
        ///
        ///!!---------------WorkPanel X
        ///compStartPos = 10                  !&lt;----------
        ///compStep = 25                      !&lt;----------
        ///MFLAGS(0).#DEFCON=1
        ///!Need to change
        ///GLOBAL REAL ErrorCompDataX(61)     !&lt;----------
        ///!Need to change
        ///!!!--------Data Here
        ///ErrorCompDataX(0)=0.0              !&lt;----------
        ///!!!.....                                       |
        ///ErrorCompDataX(60)=0.0             !&lt;------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Comp {
            get {
                return ResourceManager.GetString("Comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int s
        ///int axis
        ///int time
        ///int startpos,endpos,interv
        ///
        ///axis=0
        ///time=6000
        ///startpos=10
        ///endpos=200
        ///interv=10
        ///
        ///
        ///Global REAL Gl_Axis,Gl_StartPos,Gl_INTERVAL
        ///Global REAL ErrorCompDataX1(61)
        ///Int CollectRunFlag
        ///CollectRunFlag=0
        ///Gl_StartPos=startpos
        ///Gl_INTERVAL=interv
        ///Gl_Axis=axis
        ///
        ///IF CollectRunFlag=0
        ///   MFLAGS(Gl_Axis).#DEFCON=1
        ///END
        ///
        ///!-----------------------!
        ///!ErrorDataList
        ///!-----------------------!
        ///
        ///IF CollectRunFlag=1
        ///    MFLAGS(Gl_Axis).#DEFCON=0
        ///    CONNECT RPOS(Gl_Axis)=APOS(Gl_Axis)+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Measure {
            get {
                return ResourceManager.GetString("Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_WindowsAPICodePack {
            get {
                object obj = ResourceManager.GetObject("Microsoft_WindowsAPICodePack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_WindowsAPICodePack_Shell {
            get {
                object obj = ResourceManager.GetObject("Microsoft_WindowsAPICodePack_Shell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_WindowsAPICodePack_ShellExtensions {
            get {
                object obj = ResourceManager.GetObject("Microsoft_WindowsAPICodePack_ShellExtensions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap openFileIcon {
            get {
                object obj = ResourceManager.GetObject("openFileIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap openFolderIcon {
            get {
                object obj = ResourceManager.GetObject("openFolderIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !---------------------Home Script
        ///real dfSpeed
        ///int nAxis
        ///real safepos
        ///int onLimit
        ///
        ///!---------------------Custom Functions Here
        ///
        ///!---------------------Homing Process
        ///!!---------------Some Encoders Are Absolute
        ///!!---------------Don&apos;t Go Home After First Home
        ///!!---------------                  !&lt;----------
        ///Main:
        ///!!---------------Axis Description
        ///!!!--------Linear Axis:
        ///!!!--------Z Adjust:
        ///
        ///!--------------Axis Set And Process
        ///!----Axis Home No Index
        ///nAxis=0
        ///dfSpeed=10
        ///call AxisSet
        ///call Le [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
